# Generated by Django 3.0.5 on 2020-05-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_sign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
