# Generated by Django 3.0.5 on 2020-05-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200502_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='author',
            name='lname',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='mname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
