# Generated by Django 3.0.5 on 2020-05-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200502_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='additional_data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
