# Generated by Django 3.0.5 on 2020-05-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200511_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
