# Generated by Django 3.0.5 on 2020-06-14 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200511_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='mname',
        ),
    ]
