# Generated by Django 3.0.5 on 2020-06-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_author_mname'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='addition',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
